### ISSUE TITLE
OSError: [Errno 24] Too many open files when run a long time.

### ISSUE THREAD

**Issue by ghost** [LogicJake/rss-flow#1]
``` python
Exception in thread Thread-81839:
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/python/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/lib/python3.6/multiprocessing/pool.py", line 405, in _handle_workers
    pool._maintain_pool()
  File "/usr/local/python/lib/python3.6/multiprocessing/pool.py", line 246, in _maintain_pool
    self._repopulate_pool()
  File "/usr/local/python/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/python/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/python/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/python/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/python/lib/python3.6/multiprocessing/popen_fork.py", line 65, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
```

稳定跑了快一个月的样子。

怀疑是多线程处理的问题，之前没玩过 Python 的多线程，正在看代码中。

另外感觉处理方式不是很好，`PER` 设为 1，读取的文章有点少，不过设高了之后处理速度的确很慢。。

**Comment by LogicJake** [comment]
多进程和flask被干掉了, 现在改成用github action定时任务重新抓取,每个人保留5条,抓取一次1分钟左右,每隔15分钟重新抓取.

可以直接部署到github page
